# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Yuh Dead
tagline:          'This is how you die.'
description:      'This is how you die.'
url:              https://lorav.github.io
baseurl:          /

author:
  name:           'Lora Volkert'

paginate:         7

